/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab_.pkg8;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class El_Barrio extends javax.swing.JFrame {

    /**
     * Creates new form El_Barrio
     */
    public El_Barrio() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Admin_Menu = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AdminM = new javax.swing.JPanel();
        pro_modb = new javax.swing.JButton();
        pro_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacliente = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaproducto = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pro_nombre = new javax.swing.JTextField();
        pro_cantidad = new javax.swing.JTextField();
        pro_precio = new javax.swing.JTextField();
        pro_fecha = new javax.swing.JTextField();
        cli_nombre = new javax.swing.JTextField();
        cli_cuenta = new javax.swing.JTextField();
        cli_contraseña = new javax.swing.JTextField();
        cli_id = new javax.swing.JTextField();
        cli_saldo = new javax.swing.JTextField();
        AddPro = new javax.swing.JButton();
        AddCli = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jt_pass = new javax.swing.JTextField();
        jt_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        Admin_Menu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminM.setPreferredSize(new java.awt.Dimension(500, 500));
        AdminM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pro_modb.setText("Modificar");
        pro_modb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pro_modbMouseClicked(evt);
            }
        });
        AdminM.add(pro_modb, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        pro_delete.setText("Eliminar de Base de Datos");
        pro_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pro_deleteMouseClicked(evt);
            }
        });
        pro_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pro_deleteActionPerformed(evt);
            }
        });
        AdminM.add(pro_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 170, 20));

        tablacliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cuenta", "Contraseña", "Lista de Productos", "Identidad", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablacliente);

        AdminM.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 360, 230));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Clientes");
        AdminM.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        tablaproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Precio", "Fecha de Caducidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaproducto);

        AdminM.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 230));

        jButton2.setText("Eliminar de la Tabla");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        AdminM.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 150, 140, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Productos");
        AdminM.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jButton3.setText("Modificar");
        AdminM.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jButton4.setText("Eliminar de la Tabla");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        AdminM.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jButton5.setText("Eliminar de Base de Datos");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        AdminM.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab_/pkg8/technology-grid-data-background_4aujujcke__F0010.png"))); // NOI18N
        AdminM.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 500));

        jTabbedPane1.addTab("Menu", AdminM);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(pro_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 34, 80, -1));
        jPanel2.add(pro_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 72, 80, -1));
        jPanel2.add(pro_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 110, 80, -1));
        jPanel2.add(pro_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 148, 80, -1));
        jPanel2.add(cli_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 34, 157, -1));
        jPanel2.add(cli_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 72, 157, -1));
        jPanel2.add(cli_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 110, 64, -1));
        jPanel2.add(cli_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 148, 104, -1));
        jPanel2.add(cli_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 179, 154, -1));

        AddPro.setText("Agregar Cliente");
        AddPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProMouseClicked(evt);
            }
        });
        jPanel2.add(AddPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 233, -1, -1));

        AddCli.setText("Agreagar Producto");
        AddCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCliMouseClicked(evt);
            }
        });
        jPanel2.add(AddCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 233, -1, -1));

        jLabel5.setText("Prodcuto");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 11, -1, -1));

        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 37, -1, -1));

        jLabel7.setText("Cantidad");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 75, -1, -1));

        jLabel8.setText("Precio");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 113, -1, -1));

        jLabel9.setText("Fecha de Caducidad");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 151, -1, -1));

        jLabel10.setText("Nombre");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 37, -1, -1));

        jLabel11.setText("Cuenta");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 75, -1, -1));

        jLabel12.setText("ID");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 151, -1, -1));

        jLabel13.setText("Contraseña");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 113, -1, -1));

        jLabel15.setText("Saldo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 182, -1, -1));

        jLabel16.setText("Cliente");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 11, -1, -1));
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 377, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab_/pkg8/Mayoreo_Feria_agricultor_RadioHouse-5.jpg"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Agregar", jPanel2);

        Admin_Menu.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 520));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Acceder");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));
        jPanel1.add(jt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 70, -1));
        jPanel1.add(jt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 70, -1));

        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel3.setText("El Barrio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String usuario = jt_username.getText();
        String pass = jt_pass.getText();
        if (usuario.equals("erick123") && pass.equals("321kcire")) {
            this.Admin_Menu.setModal(true);
            Admin_Menu.pack();
            Admin_Menu.setLocationRelativeTo(this);
            Admin_Menu.setVisible(true);
        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void pro_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pro_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pro_deleteActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void AddProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProMouseClicked
        Dba db = new Dba("./Clientes.accdb");
        db.conectar();
        String nombre = cli_nombre.getText();
        int cuenta = Integer.parseInt(cli_cuenta.getText());
        String contraseña = cli_contraseña.getText();
        String lista = "";
        int id = Integer.parseInt(cli_id.getText());
        double saldo = Double.parseDouble(cli_saldo.getText());

        try {
            db.query.execute("INSERT INTO Clientes" + " (Nombre,Cuenta,Contraseña,Lista,Identidad,Saldo)" + " VALUES ('" + nombre + "', " + cuenta + ",'" + contraseña + "','" + lista + "'," + id + "," + saldo + ")");
            db.commit(); //Esto es como el flush, los comandos insert, update, y delete lo llevan siempre.
            //Pasa lo que hay de la RAM al ROM
            DefaultTableModel client = (DefaultTableModel) tablacliente.getModel();
            client.addRow(new Object[]{nombre, cuenta, contraseña, lista, id, saldo});
            JOptionPane.showMessageDialog(Admin_Menu, "Exito");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }
        db.desconectar();

        //div
//        db.conectar();
//        try {
//            db.query.execute("select Nombre, Nombre from Clientes");
//            ResultSet rs = db.query.getResultSet();
//            while (rs.next()){
//                System.out.println(rs.getInt(1) + "----->" + rs.getString(2));
//            }
//            
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
//        db.desconectar();
    }//GEN-LAST:event_AddProMouseClicked

    private void AddCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCliMouseClicked
        Dba db = new Dba("./Productos.accdb");
        db.conectar();
        String nombre = pro_nombre.getText();
        int cantidad = Integer.parseInt(pro_cantidad.getText());
        int precio = Integer.parseInt(pro_precio.getText());
        String fecha = pro_fecha.getText();

        try {
            db.query.execute("INSERT INTO Productos" + " (Nombre,Cantidad,Precio,Fecha)" + " VALUES ('" + nombre + "'," + cantidad + "," + precio + ",'" + fecha + "')");

            db.commit(); //Esto es como el flush, los comandos insert, update, y delete lo llevan siempre.
            //Pasa lo que hay de la RAM al ROM
            DefaultTableModel prod = (DefaultTableModel) tablaproducto.getModel();
            prod.addRow(new Object[]{nombre, cantidad, precio, fecha});
            JOptionPane.showMessageDialog(Admin_Menu, "Exito");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }
        db.desconectar();
    }//GEN-LAST:event_AddCliMouseClicked

    private void pro_modbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pro_modbMouseClicked
        String nam, nom, cant, prec, fecha;
        nam = JOptionPane.showInputDialog(Admin_Menu, "Nombre de Producto a Modificar.");
        nom = JOptionPane.showInputDialog(Admin_Menu, "Nuevo Nombre.");
        cant = JOptionPane.showInputDialog(Admin_Menu, "Nueva Cantidad.");
        prec = JOptionPane.showInputDialog(Admin_Menu, "Nuevo Precio.");
        fecha = JOptionPane.showInputDialog(Admin_Menu, "Nueva Fecha.");
        Dba db = new Dba("./Productos.accdb");
        db.conectar();
        try {
            db.query.execute("update Prodcutos set Cantidad ='" + Integer.parseInt(cant) + "' where Nombre ='" + nam + "'");
            db.query.execute("update Prodcutos set Precio ='" + Integer.parseInt(prec) + "' where Nombre ='" + nam + "'");
            db.query.execute("update Prodcutos set Fecha ='" + fecha + "' where Nombre ='" + nam + "'");
            db.query.execute("update Prodcutos set Nombre ='" + nom + "' where Nombre ='" + nam + "'");
            db.commit();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_pro_modbMouseClicked

    private void pro_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pro_deleteMouseClicked
        String nom;
        nom = JOptionPane.showInputDialog(Admin_Menu, "Ingerese el nombre de lo que desea eliminar.");
        Dba db = new Dba("./Productos.accdb");
        db.conectar();
        try {
            db.query.execute("delete from Productos where Nombre = '" + nom + "'");
            db.commit();

        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_pro_deleteMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        tablaproducto.remove(tablaproducto.getSelectedRow());
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        tablacliente.remove(tablacliente.getSelectedRow());
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        String nom;
        nom = JOptionPane.showInputDialog(Admin_Menu, "Ingerese el nombre de lo que desea eliminar.");
        Dba db = new Dba("./Clientes.accdb");
        db.conectar();
        try {
            db.query.execute("delete from Productos where Nombre = '" + nom + "'");
            db.commit();

        } catch (SQLException e) {
            e.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(El_Barrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(El_Barrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(El_Barrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(El_Barrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new El_Barrio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCli;
    private javax.swing.JButton AddPro;
    private javax.swing.JPanel AdminM;
    private javax.swing.JDialog Admin_Menu;
    private javax.swing.JTextField cli_contraseña;
    private javax.swing.JTextField cli_cuenta;
    private javax.swing.JTextField cli_id;
    private javax.swing.JTextField cli_nombre;
    private javax.swing.JTextField cli_saldo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jt_pass;
    private javax.swing.JTextField jt_username;
    private javax.swing.JTextField pro_cantidad;
    private javax.swing.JButton pro_delete;
    private javax.swing.JTextField pro_fecha;
    private javax.swing.JButton pro_modb;
    private javax.swing.JTextField pro_nombre;
    private javax.swing.JTextField pro_precio;
    private javax.swing.JTable tablacliente;
    private javax.swing.JTable tablaproducto;
    // End of variables declaration//GEN-END:variables
}
